# Generated by Django 4.0.5 on 2022-10-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ticketing", "0002_alter_review_ticket_ticket_unique ticketing"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique Ticketing",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(fields=("user",), name="unique review"),
        ),
    ]
