# Generated by Django 4.0.5 on 2022-11-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ticketing", "0003_remove_ticket_unique ticketing_review_unique review"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique review",
        ),
    ]
