# Generated by Django 4.0.5 on 2022-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0002_alter_following_followed_user_alter_following_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'followed_user'), name='unique following'),
        ),
    ]
